#!/bin/bash
. ../menu

download_eww(){
    pushd ~
    git clone https://github.com/elkowar/eww
    popd
}

build_eww(){
    pushd ~

    cd eww
    if [ $XDG_SESSION_TYPE = 'wayland' ];then
        echo "RUNNING ON WAYLAND"
        cargo build --release --no-default-features --features=wayland
    elif [ $XDG_SESSION_TYPE = 'wayland' ];then
        echo "RUNNING ON X11"
        cargo build --release --no-default-features --features x11
    else 
        echo "UNKNOWN XDG SESSION TYPE"
    fi
    popd
}

run_eww(){

    pushd ~
    cd eww

    cd target/release
    chmod +x ./eww
    ./eww daemon
    ./eww open n.n
    popd
}

eww_menu(){
    menu "eww/eww"
}