#!/bin/bash

wallpaper_folder=./wallpapers

files=($image_folder/*)

get_last_image_index(){
	echo "nothing"
}



change_image_names(){
	counter=0
	for image in $files; do
		if [ -f $image ]; then
			((counter++))
			echo $counter
			# echo $image
			# mv $image $image_folder/fak_$counter	
		fi
	done

}



main(){

	echo $wallpaper_folder
	echo $files
	get_last_image_index
	change_image_names
}

main