#!/bin/bash


image_folder=./wallpapers

files=("$image_folder"/*)
echo $files

get_last_image_index(){
	echo "nothing"
}



counter=0
for image in $files; do
	if [ -f "$image" ]; then
		((counter++))
		echo $counter
		echo $file		
		# mv $image $image_folder/wallpaper_$counter	
	fi
done
