#!/bin/bash

sudo pacman -Syu


#Starship theme
curl -sS https://starship.rs/install.sh | sh
echo 'eval "$(starship init bash)"' >> ~/.bashrc




# Personal system packages
sudo pacman -S usbutils rsync bat
# Personal dependencies
sudo pacman -S firefox git inkscape blender code usbutils rsync

# Policy Kit
sudo pacman -S gnome-keyring polkit-gnome

# File Manager
sudo pacman -S nautilus


#bluetooth
sudo pacman -S bluez bluez-utils blueman

sudo pacman -S meson clang


#sound -> helvum
git clone https://gitlab.freedesktop.org/pipewire/helvum.git
cd helvum
meson setup build && cd build
meson compile
meson install




# App Launcher
sudo pacman -S wofi
:
#PARU -> ARCH USER REPOSITORY (AUR) HELPER
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

cd ~
sudo pacman -S swaybg
sudo paru -S waypaper-git


sudo pacman -S libvirt

sudo pacman -S iptables-nft dnsmasq
sudo pacman -S virt-manager


sudo systemctl enable libvirtd.socket



